services:
  database: 
    - name: hngx2
      databaseName: 
      user: postgres
  app:
    - type: web
      name: hngx-s2
      env: web
      runtime: python
      buildCommand: |
        "./build.sh"
      startCommand: gunicorn config.wsgi:application
      envVars:
        - key: DATABASE_URL
          fromDatabase:
            name: hngx2
            property: connectionString
        - key: SECRET_KEY
          generateValue: true
        - key: WEB_CONCURRENCY
          value: 4
