services:
  - type: web
    name: hngx-s2
    env: web
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: False
      - key: WEB_CONCURRENCY
        value: 4