# Generated by Django 4.2.5 on 2023-09-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="age",
            field=models.PositiveIntegerField(default=True),
            preserve_default=False,
        ),
    ]
